# Generated by Django 5.2.7 on 2026-02-19 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Название видео', max_length=255)),
                ('file', models.FileField(blank=True, help_text='Загружаемый файл', upload_to='videos/')),
                ('source_url', models.CharField(blank=True, help_text='URL, для загрузки видео', max_length=1024, null=True)),
                ('status', models.CharField(choices=[('not_processed', 'Не обработан'), ('processing', 'В обработке'), ('processed', 'Обработан')], default='not_processed', help_text='Статус обработки видео', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='Категория события', max_length=32)),
                ('start_time', models.PositiveIntegerField(help_text='Начало события в секундах от начала видео')),
                ('end_time', models.PositiveIntegerField(help_text='Конец события в секундах от начала видео')),
                ('confidence', models.FloatField(help_text='Уверенность')),
                ('description', models.TextField(blank=True, help_text='Краткое текстовое описание события')),
                ('highlight', models.URLField(blank=True, help_text='Ссылка на вырезку/плейлист/диапазон', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(help_text='Видео, к которому относится хедлайн', on_delete=django.db.models.deletion.CASCADE, related_name='headlines', to='main.video')),
            ],
            options={
                'verbose_name': 'Хедлайн',
                'verbose_name_plural': 'Хедлайны',
                'ordering': ['-created_at'],
            },
        ),
    ]
