# Generated by Django 5.2.7 on 2026-02-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Длительность видео в секундах', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('not_processed', 'Не обработан'), ('downloading', 'Идёт загрузка'), ('processing', 'В обработке'), ('processed', 'Обработан')], default='not_processed', help_text='Статус обработки видео', max_length=32),
        ),
    ]
