# Generated by Django 5.2.7 on 2026-02-19 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_headline_to_highlight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlight',
            options={'ordering': ['-created_at'], 'verbose_name': 'Хайлайт', 'verbose_name_plural': 'Хайлайты'},
        ),
        migrations.AlterField(
            model_name='highlight',
            name='video',
            field=models.ForeignKey(help_text='Видео, к которому относится хайлайт', on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='main.video'),
        ),
    ]
