# Generated by Django 5.2.7 on 2026-02-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_highlight_options_alter_highlight_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='Является ли хайлайт собственным промтом пользователя'),
        ),
    ]
