# Generated by Django 5.2.7 on 2026-02-19 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает запуска'), ('running', 'Выполняется'), ('success', 'Успешно завершено'), ('failed', 'Завершено с ошибкой')], default='pending', help_text='Статус выполнения задания', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, help_text='Ответ от ML-сервиса', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Текст ошибки')),
                ('video', models.ForeignKey(help_text='Видео', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main.video')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
    ]
