# Generated by Django 5.2.7 on 2026-02-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Название видео', max_length=255)),
                ('file', models.FileField(help_text='Загружаемый файл', upload_to='videos/')),
                ('source_url', models.URLField(blank=True, help_text='URL, по которому можно скачать видео (альтернатива прямой загрузке файла).', null=True)),
                ('domain', models.CharField(choices=[('traffic', 'ДТП'), ('factory', 'Производство'), ('fight', 'Драки')], help_text='Домен', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
