# Generated by Django 5.2.7 on 2026-02-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='domain',
        ),
        migrations.AlterField(
            model_name='video',
            name='source_url',
            field=models.URLField(blank=True, help_text='URL, для загрузки видео', null=True),
        ),
    ]
