# Generated by Django 5.2.7 on 2026-02-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configtask',
            name='promt',
            field=models.TextField(blank=True, help_text='Собственный промт пользователя', null=True),
        ),
    ]
