# Generated by Django 5.2.7 on 2026-02-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_remove_video_domain_alter_video_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('not_processed', 'Не обработан'), ('processing', 'В обработке'), ('processed', 'Обработан')], default='not_processed', help_text='Статус обработки видео', max_length=32),
        ),
    ]
