# Generated by Django 5.2.7 on 2026-02-18 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_video_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at'], 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('DTP', 'ДТП'), ('INDUSTRIAL', 'Промышленное'), ('FIGHT', 'Драка'), ('OTHER', 'Другое/Нет события')], help_text='Категория события', max_length=32)),
                ('start_time', models.PositiveIntegerField(help_text='Начало события в секундах от начала видео')),
                ('end_time', models.PositiveIntegerField(help_text='Конец события в секундах от начала видео')),
                ('confidence', models.FloatField(help_text='Уверенность')),
                ('description', models.TextField(blank=True, help_text='Краткое текстовое описание события')),
                ('highlight', models.URLField(blank=True, help_text='Ссылка на вырезку/плейлист/диапазон', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(help_text='Видео, к которому относится хедлайн', on_delete=django.db.models.deletion.CASCADE, related_name='headlines', to='logistic.video')),
            ],
            options={
                'verbose_name': 'Хедлайн',
                'verbose_name_plural': 'Хедлайны',
                'ordering': ['-created_at'],
            },
        ),
    ]
