# Generated by Django 5.2.7 on 2026-02-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0004_alter_video_options_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, help_text='Загружаемый файл', upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='source_url',
            field=models.CharField(blank=True, help_text='URL, для загрузки видео', max_length=1024, null=True),
        ),
    ]
