# Generated by Django 5.2.7 on 2026-02-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0006_alter_headline_event_type_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='ConfigTask',
        ),
    ]
